In [1]:
from openai import OpenAI
import dotenv
import rich
dotenv.load_dotenv('/Users/shepardxia/Desktop/directory/commonsense/.env')

True

In [2]:
import torch
from torch import nn
import pandas as pd
import mrf
import mrf_data
import json


In [3]:
import llm
import json

In [4]:
initial_message = [{"role": "system", "content": 'You are a statistician interviewing for a market analytics position. ' +\
                    'During the interview, you are asked to analyze the nightly prices of Airbnb listings in the United States in 2017. ' +\
                    'Although you do not have access to any actual data, you are known for your ability to identify structures and relationships among data variables. ' +\
                    'Rely on commonsense guesses, intuition, and experience to make broad generalizations. ' +\
                    'The interviewer will guide your thinking through a set of predefined questions. ' +\
                    'Aim to be thoughtful but also general and concise. ' +\
                    'Reason through the problem concisely before giving a structured answer in the end of your response. ' +\
                    'You should not give additional justifications after giving the answers.'},]

In [5]:
json_dialogue = [{"role": "system", "content": 'You are a transcriber tasked to convert parts of a statistician interview for a market analytics position into JSON. ' +\
                    'During the interview, the interviewee was asked to analyze the nightly prices of Airbnb listings in the United States in 2017. ' +\
                    'The JSON has two parts, Variables and Constraints. Constraints can be left out if not mentioned yet. \nVariables define the variable names and their possible values. For example, Variable X with Values x1, x2, and x3. \n\nEach constraint entry has three parts: (Batch) Target, Condition, and (Batch) Probability. Target an Condition also consist of names and possible values. Probability denotes conditional or unconditional probabilities in interval or number. \nFor example, if there is P(Y=y1|X=x1)=0.9, then Target has Variable Y with Value y1, and Condition Variable X Value x1, and a probability of 0.9. \nIf there are multiple conditions in the value, then we are conditioning on the collection of them: P(Y=y1|X=x1 or X=x2) then Condition has Variable X Value x1, x2.\nThere can also be no conditions, like P(X=x1), and then Condition is left empty.\n For simplicity, we also have Batch notation:\nIf conditioned on x1 probability of y1 is 0.7 and of y2 is 40%-50%, then we use Batch Variable with Name Y and Values y1, y2. In this case there is Batch Probability which must has two entries, 0.7 and [0.4, 0.5].\n When transcribing, always provide the existing Variables, but you do not need to include the previous constraints. After the initial training warmup (with hints), you will start converting the actual dialogue. Remember that the warmup is to provide examples, not for actual entries afterwards.'},]

# put comments in JSON
user_1 = '[warmup] After consideration, I think there should be three variables: \nA with values a1, a2, a3\n B with values b1, b2\n C with values c1, c2' 

assistant_1 = '\n{\n  "Variables": [\n    {\n      "Name": "A",\n      "Value": ["a1", "a2", "a3"]\n    },\n    {\n      "Name": "B",\n      "Value": ["b1", "b2"]\n    },\n    {\n      "Name": "C",\n      "Value": ["c1", "c2"]\n    }\n  ]}'

json_dialogue.append({"role": "user", "content": user_1})
json_dialogue.append({"role": "assistant", "content": assistant_1})


user_2 = '[warmup] Conditional probability of a1 given b2: 10%-20%\n' +\
    '(0.1<P(A=a1|B=b2)<0.2\n\n)' +\
    'Conditional probability of c2 given a1 or a2: 50% \n' +\
    '(P(C=c2|A=a1 or A=a2)=0.5\n\n)'


assistant_2 = '\n{\n  "Variables": [\n    {\n      "Name": "A",\n      "Value": ["a1", "a2", "a3"]\n    },\n    {\n      "Name": "B",\n      "Value": ["b1", "b2"]\n    },\n    {\n      "Name": "C",\n      "Value": ["c1", "c2"]\n    }\n  ],\n  "Constraints": [\n    {\n      "Target": [\n        {\n          "Name": "A",\n          "Value": ["a1"]\n        }\n      ],\n      "Condition": [\n        {\n          "Name": "B",\n          "Value": ["b2"]\n        },\n        {\n          "Name": "C",\n          "Value": ["c1"]\n        }\n      ],\n      "Probability": [0.1, 0.2]\n    },\n    {\n      "Target": [\n        {\n          "Name": "C",\n          "Value": ["c2"]\n        }\n      ],\n      "Condition": [\n        {\n          "Name": "A",\n          "Value": ["a1", "a2"]\n        }\n      ],\n      "Probability": [0.5]\n    }\n  ]\n}'


json_dialogue.append({"role": "user", "content": user_2})
json_dialogue.append({"role": "assistant", "content": assistant_2})


user_3 = '[warmup] Marginal probability of a2: 0.8-0.9\n' +\
    '(0.8<P(A=a2)<0.9\n\n)' + \
    'C: c2:\n' +\
    'b1: 30%-40%, b2: 60% (in this case we use Batch for simplicity, as multiple probabilities of Variable B conditioned on c1 is given)\n' +\
    '(0.3<P(B=b1|C=c1)<0.4, P(B=b2|C=c1)=0.6\n\n)'

assistant_3 = '\n{\n  "Variables": [\n    {\n      "Name": "A",\n      "Value": ["a1", "a2", "a3"]\n    },\n    {\n      "Name": "B",\n      "Value": ["b1", "b2"]\n    },\n    {\n      "Name": "C",\n      "Value": ["c1", "c2"]\n    }\n  ],\n  "Constraints": [\n    {\n      "Target": [\n        {\n          "Name": "A",\n          "Value": ["a1"]\n        }\n      ],\n      "Condition": [\n        {\n          "Name": "B",\n          "Value": ["b2"]\n        },\n        {\n          "Name": "C",\n          "Value": ["c1"]\n        }\n      ],\n      "Probability": [0.1, 0.2]\n    },\n    {\n      "Target": [\n        {\n          "Name": "C",\n          "Value": ["c2"]\n        }\n      ],\n      "Condition": [\n        {\n          "Name": "A",\n          "Value": ["a1", "a2"]\n        }\n      ],\n      "Probability": [0.5]\n    },\n    {\n      "Batch Target": [\n        {\n          "Name": "B",\n          "Value": ["b1", "b2"]\n        }\n      ],\n      "Condition": [\n        {\n          "Name": "C",\n          "Value": ["c2"]\n        }\n      ],\n      "Batch Probability": [\n        [0.3, 0.4],\n        [0.6]\n      ]\n    }\n  ]\n}'


json_dialogue.append({"role": "user", "content": user_3})
json_dialogue.append({"role": "assistant", "content": assistant_3})

# start with coarse gram facts bi->tri

In [6]:
import importlib
importlib.reload(llm)
#agent = llm.LLM(initial_message, model='gpt-3.5-turbo', json_format=formatq)
agent = llm.LLM(initial_message, json_dialogue=json_dialogue)
agent.reset()

In [7]:
binq = 'To model the nightly price of Airbnb listings in 2017, we need to first divide the price into a few ranges. Think about the parametric statistical distribution to approximate the price. Divide the price into a few ranges accordingly.'

brainq = "Let's brainstorm the factors that might affect or determine the prices of Airbnb listings. Think about the obvious and commonsense aspects that would influence pricing. Reason through how these variables might interact or correlate with each other. "

broadq = "What are some salient interactions? Consider how these variables might influence each other, rather than just their impact on price. Think about correlations and dependencies among the variables themselves."

moreq = "Take your time to reason through additional variables and their possible interactions. Consider other factors that might influence the price, or other existing variables."

varq = "Pick some of the most important variables (at most 6), what exhaustively are their possible values? These values should be few but also concrete, and mutually exclusive. In the end, also include the price, with the ranges you gave."

# p(x)  You can give a credible interval if unsure.
margq = "Well, what are the individual marginal probabilities of all the values of these variables? Give a best guess."

# p(price|bedroom)
pricecondq = 'How would they affect the price? Suggest the probability of price, conditioned on each of these variable values. Give a best guess. However, if you think that the variable or value does not affect the price much, you can skip it.'

# p(bedroom=2|property_type=entire_house)
#interactq = "How do you think the rest of the chosen variables interact with each other? Avoid duplicates from before. After reasoning through, suggest the conditional probability that captures those interaction."
# dependencies <-> interaction? point-wise mutual information 
interactq = "What are some dependencies among these variables other than price? Suggest the conditional probability that captures those interaction. Suggest with the probability value."

acoq = "Good, suggest a couple more."


chains = [binq, brainq, broadq, moreq, varq]
saws = [None, margq, pricecondq, interactq]



In [329]:
print(agent.button(chains, saws))

user : To model the nightly price of Airbnb listings in 2017, we need to first divide the price into a few ranges. Think about the parametric statistical distribution to approximate the price. Divide the price into a few ranges accordingly.


--------------------------------------------------------------------------------------


assistant : To model the nightly price of Airbnb listings, we can start by assuming that the distribution of prices follows a log-normal distribution, which is common for prices and income data due to their positive skewness and non-negative values. This means that the logarithm of the prices is normally distributed.

Given this assumption, we can divide the price into several ranges, considering the typical characteristics of such a distribution. Here are the ranges we might use:

1. **Low Range**: $0 - $50
2. **Lower-Mid Range**: $51 - $100
3. **Mid Range**: $101 - $200
4. **Upper-Mid Range**: $201 - $500
5. **High Range**: $501 and above

These ranges shoul

In [360]:
vars = agent.var_json
constraints_list = agent.cons_json
print(vars)

# pickle
import pickle

with open('vars.pkl', 'wb') as f:
    pickle.dump(vars, f)
with open('cons.pkl', 'wb') as f:
    pickle.dump(constraints_list, f)
    

[{'Name': 'Location (City/Town)', 'Value': ['Major City', 'Tourist Destination', 'Small City/Town']}, {'Name': 'Property Type', 'Value': ['Entire Home/Apartment', 'Private Room', 'Shared Space']}, {'Name': 'Amenities', 'Value': ['Basic', 'Standard', 'Premium']}, {'Name': 'Seasonality', 'Value': ['Peak Season', 'Off-Peak Season']}, {'Name': 'Host Experience', 'Value': ['New Host', 'Experienced Host', 'Superhost']}, {'Name': 'Guest Reviews and Ratings', 'Value': ['High Rating', 'Moderate Rating', 'Low Rating']}, {'Name': 'Price Ranges', 'Value': ['Low Range', 'Lower-Mid Range', 'Mid Range', 'Upper-Mid Range', 'High Range']}]


In [9]:
# load pickle
import pickle

with open('vars.pkl', 'rb') as f:
    vars = pickle.load(f)
with open('cons.pkl', 'rb') as f:
    constraints_list = pickle.load(f)

In [71]:
from importlib import reload
reload(mrf)
reload(mrf_data)

# guidance package?
test = mrf.Brute()
ret = test.from_json(vars=vars, constraints=constraints_list)
test.update(10000)
test.infer_print()

-----------------------------------------------
Finished building
Features:  115
Constraints:  114
-----------------------------------------------


  1%|          | 107/10000 [00:00<00:09, 1063.80it/s]

Loss:  tensor(5.0354, grad_fn=<SumBackward0>) tensor(0.0442, grad_fn=<MeanBackward0>)


 22%|██▏       | 2167/10000 [00:02<00:06, 1194.14it/s]

Loss:  tensor(0.1047, grad_fn=<SumBackward0>) tensor(0.0009, grad_fn=<MeanBackward0>)


 42%|████▏     | 4167/10000 [00:03<00:04, 1206.04it/s]

Loss:  tensor(0.0961, grad_fn=<SumBackward0>) tensor(0.0008, grad_fn=<MeanBackward0>)


 62%|██████▏   | 6160/10000 [00:05<00:03, 1212.91it/s]

Loss:  tensor(0.0927, grad_fn=<SumBackward0>) tensor(0.0008, grad_fn=<MeanBackward0>)


 81%|████████  | 8113/10000 [00:07<00:01, 985.61it/s] 

Loss:  tensor(0.0909, grad_fn=<SumBackward0>) tensor(0.0008, grad_fn=<MeanBackward0>)


100%|██████████| 10000/10000 [00:09<00:00, 1084.34it/s]

Loss:  tensor(0.0898, grad_fn=<SumBackward0>) tensor(0.0008, grad_fn=<MeanBackward0>)
Conditions:  None
tensor([-1., -1., -1., -1., -1., -1.,  0.])
tensor([-1., -1., -1., -1., -1., -1.,  1.])
tensor([-1., -1., -1., -1., -1., -1.,  2.])
tensor([-1., -1., -1., -1., -1., -1.,  3.])
tensor([-1., -1., -1., -1., -1., -1.,  4.])
          0
0  0.158134
1  0.292306
2  0.320774
3  0.168299
4  0.060486


[]

In [37]:
for item in ret:
    if item not in ret:

In [349]:
test.vars_print()


Variable:  Location (City/Town)
Value:  Major City, Tourist Destination, Small City/Town 


Variable:  Property Type
Value:  Entire Home/Apartment, Private Room, Shared Space 


Variable:  Amenities
Value:  Basic, Standard, Premium 


Variable:  Seasonality
Value:  Peak Season, Off-Peak Season 


Variable:  Host Experience
Value:  New Host, Experienced Host, Superhost 


Variable:  Guest Reviews and Ratings
Value:  High Rating, Moderate Rating, Low Rating 


Variable:  Price Ranges
Value:  Low Range, Lower-Mid Range, Mid Range, Upper-Mid Range, High Range 



In [61]:
print(test.nvars())
print(test.nfeatures())



7
115


In [62]:
print(test.var_name2ind('Seasonality'))
print(test.var_ind2name(2))
print(test.val_name2ind('Seasonality', 'Off-Peak Season'))
print(test.val_ind2name(2, 1))

3
Amenities
1
Standard


In [69]:
di = dict()
di['Location (City/Town)'] = ['Major City']
#di[1] = [1]
test.marg('Price Ranges', di)


tensor([0.0674, 0.2024, 0.4025, 0.2504, 0.0773])

In [68]:
test.infer_print(target=0, conditions=['Off-Peak Season', 'Urban'])

Conditions:  ['Off-Peak Season', 'Urban']
tensor([ 0., -1., -1., -1., -1., -1., -1.])
tensor([ 1., -1., -1., -1., -1., -1., -1.])
tensor([ 2., -1., -1., -1., -1., -1., -1.])
          0
0  0.378854
1  0.278314
2  0.342832


[]

In [26]:
test.vars_print()


Geographic Location ['Urban', 'Suburban', 'Rural', 'Tourist Destination']
Property Type ['Entire Home/Apartment', 'Private Room', 'Shared Room', 'Unique Property']
Seasonality ['Peak Season', 'Off-Peak Season', 'Shoulder Season']
Amenities ['Basic', 'Moderate', 'Luxury']
Booking Lead Time ['Last-Minute', 'Short-Term', 'Medium-Term', 'Long-Term']
Price ['Low Range', 'Mid-Low Range', 'Mid Range', 'Mid-High Range', 'High Range']
tensor([4, 4, 3, 3, 4, 5], dtype=torch.int32)


In [27]:
ret = test.infer_print()

Conditions:  None
                       0
Low Range       0.137715
Mid-Low Range   0.324761
Mid Range       0.309258
Mid-High Range  0.156726
High Range      0.071541


In [30]:
ret = test.infer_print(conditions=['Entire Home/Apartment', 'Urban'])

Conditions:  ['Entire Home/Apartment', 'Urban']
                       0
Low Range       0.013354
Mid-Low Range   0.122281
Mid Range       0.287852
Mid-High Range  0.332170
High Range      0.244343


In [99]:
ret = test.infer_print()

Conditions:  None
                     0
$0 - $50      0.156319
$50 - $100    0.242188
$100 - $200   0.288569
$200 - $500   0.191271
$500 - $1000  0.087047
$1000+        0.034605


In [116]:
ret = test.infer_print(conditions=['2 Bedrooms', 'Urban'])

Conditions:  ['2 Bedrooms', 'Urban']
                     0
$0 - $50      0.078429
$50 - $100    0.158255
$100 - $200   0.333385
$200 - $500   0.251176
$500 - $1000  0.123529
$1000+        0.055226


In [115]:
ret = test.infer_print(conditions=['2 Bedrooms', 'Urban', 'Peak Season', 'Luxury', 'Entire Home/Apartment'])


Conditions:  ['2 Bedrooms', 'Urban', 'Peak Season', 'Luxury', 'Entire Home/Apartment']
                     0
$0 - $50      0.003279
$50 - $100    0.022148
$100 - $200   0.314232
$200 - $500   0.281583
$500 - $1000  0.239166
$1000+        0.139592


In [121]:
cond = lambda x: x[x['bedrooms'] == 2]
dat.marg(cond=cond)

-1 - 50: 	0.92%
50 - 100: 	10.96%
100 - 200: 	46.99%
200 - 500: 	36.36%
500 - 1000: 	3.97%
1000 - 1999: 	0.80%


In [133]:
from importlib import reload

reload(mrf_data)
dat = mrf_data.data()
dat.set_bins([50, 100, 200, 500, 1000])

All columns available:  Index(['id', 'log_price', 'property_type', 'room_type', 'amenities',
       'accommodates', 'bathrooms', 'bed_type', 'cancellation_policy',
       'cleaning_fee', 'city', 'description', 'first_review',
       'host_has_profile_pic', 'host_identity_verified', 'host_response_rate',
       'host_since', 'instant_bookable', 'last_review', 'latitude',
       'longitude', 'name', 'neighbourhood', 'number_of_reviews',
       'review_scores_rating', 'thumbnail_url', 'zipcode', 'bedrooms', 'beds',
       'price'],
      dtype='object')
Columns used:  ['log_price', 'bathrooms', 'property_type', 'room_type', 'accommodates', 'bedrooms', 'beds', 'amenities', 'review_scores_rating', 'city']


In [134]:
dat.unique('city')

['NYC' 'SF' 'DC' 'LA' 'Chicago' 'Boston']


In [124]:
dat.describe('property_type')

count         74019
unique           35
top       Apartment
freq          48929
Name: property_type, dtype: object


In [129]:
dat.marg('property_type')

Apartment: 	66.10%
House: 	22.29%
Condominium: 	3.59%
Loft: 	1.68%
Townhouse: 	2.29%
Hostel: 	0.09%
Guest suite: 	0.17%
Bed & Breakfast: 	0.62%
Bungalow: 	0.49%
Guesthouse: 	0.67%
Dorm: 	0.19%
Other: 	0.82%
Camper/RV: 	0.13%
Villa: 	0.24%
Boutique hotel: 	0.09%
Timeshare: 	0.10%
In-law: 	0.10%
Boat: 	0.09%
Serviced apartment: 	0.03%
Castle: 	0.02%
Cabin: 	0.10%
Treehouse: 	0.01%
Tipi: 	0.00%
Vacation home: 	0.01%
Tent: 	0.02%
Hut: 	0.01%
Casa particular: 	0.00%
Chalet: 	0.01%
Yurt: 	0.01%
Earth House: 	0.01%
Parking Space: 	0.00%
Train: 	0.00%
Cave: 	0.00%
Lighthouse: 	0.00%
Island: 	0.00%


In [52]:
messages = agent.iter_chat(new_messages=chains)

user : To model the nightly price of Airbnb listings in 2017, we need to first the price into a few ranges. Think about the parametric statistical distribution to approximate the price. Divide the price into a few ranges accordingly.


--------------------------------------------------------------------------------------


assistant : Considering the wide range of nightly prices for Airbnb listings, we can divide the prices into four ranges: 
1. Low prices (e.g., $0-$50)
2. Medium-low prices (e.g., $51-$100)
3. Medium-high prices (e.g., $101-$200)
4. High prices (e.g., $201 and above)

For modeling the nightly prices, we can consider using a skewed distribution like the log-normal distribution. This distribution is commonly used for modeling positive-valued variables that are skewed to the right, which could be suitable for the distribution of nightly prices for Airbnb listings.


--------------------------------------------------------------------------------------


user : Let's brai

In [12]:
agent.reset()

In [45]:
agent.initial_message

[{'role': 'system',
  'content': 'You are a statistician interviewing for a market analytics position. During the interview, you are asked to analyze the nightly prices of Airbnb listings in the United States in 2017. Although you do not have access to any actual data, you are known for your ability to identify structures and relationships among data variables. Rely on commonsense guesses, intuition, and experience to make broad generalizations. The interviewer will guide your thinking through a set of predefined questions. Aim to be thoughtful but also general and conside. Reason through the problem considely before giving a structured answer in the end of your response. You should not give additional justifications after giving the answers.'}]

In [77]:
messages = agent.continue_from_last(new_user_message=acoq)

user : Good, suggest a couple more.


--------------------------------------------------------------------------------------


assistant : Another potential dependency among the variables is the interaction between **Property Type** and **Seasonality**. Certain property types may be more popular or in demand during specific seasons.

Conditional probability based on this dependency:
- Given Entire Home/Apartment:
  - Probability of Peak Season: 40%
  - Probability of Shoulder Season: 30%
  - Probability of Low Season: 30%

- Given Private Room:
  - Probability of Peak Season: 30%
  - Probability of Shoulder Season: 40%
  - Probability of Low Season: 30%

- Given Shared Room:
  - Probability of Peak Season: 20%
  - Probability of Shoulder Season: 30%
  - Probability of Low Season: 50%

This conditional probability captures how the type of property may interact with seasonality, reflecting potential shifts in demand for different property types during various seasons.

Another dependency

In [67]:
agent.current_dialogue

[{'role': 'system',
  'content': 'You are a statistician interviewing for a market analytics position. During the interview, you are asked to analyze the nightly prices of Airbnb listings in the United States in 2017. Although you do not have access to any actual data, you are known for your ability to identify structures and relationships among data variables. Rely on commonsense guesses, intuition, and experience to make broad generalizations. The interviewer will guide your thinking through a set of predefined questions. Aim to be thoughtful but also general and conside. Reason through the problem considely before giving a structured answer in the end of your response. You should not give additional justifications after giving the answers.'},
 {'role': 'user',
  'content': 'To model the nightly price of Airbnb listings in 2017, we need to first the price into a few ranges. Think about the parametric statistical distribution to approximate the price. Divide the price into a few range

In [78]:
messages = agent.get_json()

user : Now, I need you to translate the variables and constraints (leave constraints empty if not discussed yet) discussed so far into JSON. Do not forget about price. Follow the following example as format, if there are two variables, a with values a1, a2, a3, and b with values b1, b2. 
Probability of a1 given b2 is 10%~20%, of a2 given b1 is 50%, and marginal probability of a1 (i.e. not conditioned on any variable) is 20%~30%. This would translate into 
 {
  "variables": {
    "a": ["a1", "a2", "a3"],
    "b": ["b1", "b2"]
  },
  "probabilities": [
    [["b", "b2"], ["a", "a1"], [0.1, 0.2]],
    [["b", "b1"], ["a", "a2"], [0.5]],
    [null, ["a", "a1"], [0.2, 0.3]]
  ]
}
We already have the following json:
{
  "variables": {
    "Location": ["Urban", "Suburban", "Rural"],
    "Property Type": ["Entire Home/Apartment", "Private Room", "Shared Room"],
    "Accommodation Size": ["Small", "Medium", "Large"],
    "Amenities": ["Basic", "Standard", "Premium"],
    "Seasonality": ["Low Seas

In [79]:
agent.prent(agent.current_dialogue)

system : You are a statistician interviewing for a market analytics position. During the interview, you are asked to analyze the nightly prices of Airbnb listings in the United States in 2017. Although you do not have access to any actual data, you are known for your ability to identify structures and relationships among data variables. Rely on commonsense guesses, intuition, and experience to make broad generalizations. The interviewer will guide your thinking through a set of predefined questions. Aim to be thoughtful but also general and conside. Reason through the problem considely before giving a structured answer in the end of your response. You should not give additional justifications after giving the answers.


--------------------------------------------------------------------------------------


user : To model the nightly price of Airbnb listings in 2017, we need to first the price into a few ranges. Think about the parametric statistical distribution to approximate the pr

In [33]:
print([agent.current_json])

['{\n  "variables": {\n    "Location": ["Urban", "Suburban", "Rural"],\n    "Property Type": ["Apartment", "House", "Villa"],\n    "Seasonality": ["Peak season", "Off-peak season"],\n    "Size and Capacity": ["Small (1-2 guests)", "Medium (3-6 guests)", "Large (7+ guests)"],\n    "Reviews and Ratings": ["Low ratings", "Average ratings", "High ratings"],\n    "Price Range": ["Low ($0 - $50)", "Medium ($51 - $150)", "High ($151 - $300)", "Luxury ($301+)"]\n  },\n  "probabilities": [\n    [null, "Location", [0.4, 0.6, 0.3, 0.5, 0.1, 0.3]],\n    [null, "Property Type", [0.4, 0.6, 0.3, 0.5, 0.1, 0.3]],\n    [null, "Seasonality", [0.4, 0.6, 0.3, 0.5]],\n    [null, "Size and Capacity", [0.3, 0.5, 0.4, 0.6, 0.1, 0.3]],\n    [null, "Reviews and Ratings", [0.2, 0.4, 0.4, 0.6, 0.2, 0.4]]\n  ]\n}']


In [71]:
ret = agent.backspace()

system : You are a statistician interviewing for a market analytics position. During the interview, you are asked to analyze the nightly prices of Airbnb listings in the United States in 2017. Although you do not have access to any actual data, you are known for your ability to identify structures and relationships among data variables. Rely on commonsense guesses, intuition, and experience to make broad generalizations. The interviewer will guide your thinking through a set of predefined questions. Aim to be thoughtful but also general and conside. Reason through the problem considely before giving a structured answer in the end of your response. You should not give additional justifications after giving the answers.


--------------------------------------------------------------------------------------


user : To model the nightly price of Airbnb listings in 2017, we need to first the price into a few ranges. Think about the parametric statistical distribution to approximate the pr

In [199]:
agent.current_dialogue

In [48]:
updated_messages = agent.continue_from_last(margq)

user : Well, what are the marginal probabilities of all the variables? You can give a small range whose width reflect your confidence.


--------------------------------------------------------------------------------------


assistant : 1. Location:
   - Urban: 0.4 - 0.6
   - Suburban: 0.3 - 0.5
   - Rural: 0.1 - 0.3

2. Property Type:
   - Apartment: 0.4 - 0.6
   - House: 0.3 - 0.5
   - Condo: 0.1 - 0.3

3. Size of the Property:
   - Small: 0.3 - 0.5
   - Medium: 0.3 - 0.5
   - Large: 0.1 - 0.3

4. Amenities Offered:
   - Basic: 0.4 - 0.6
   - Standard: 0.3 - 0.5
   - Luxury: 0.1 - 0.3

5. Seasonality:
   - Peak: 0.4 - 0.6
   - Off-Peak: 0.3 - 0.5

Price Range:
   - Low: 0.3 - 0.5
   - Medium: 0.3 - 0.5
   - High: 0.1 - 0.3


--------------------------------------------------------------------------------------




In [137]:
print([assistant_response])

['\n{\n  "variables": {\n    "LocationType": ["Urban", "Suburban", "Rural"],\n    "PropertyType": ["EntireHomeApartment", "PrivateRoom", "SharedRoom", "UniqueProperty"],\n    "SizeCapacity": ["Small", "Medium", "Large"],\n    "Amenities": ["Basic", "Standard", "Luxury"],\n    "Seasonality": ["PeakSeason", "OffPeakSeason"],\n    "HostReputation": ["NewHost", "AverageHost", "HighlyRatedHost", "Superhost"],\n    "DemandLocalEvents": ["NormalDemand", "HighDemand"],\n    "LengthOfStay": ["ShortStay", "MediumStay", "LongStay"],\n    "Price": ["EconomyRange", "StandardRange", "PremiumRange", "LuxuryRange", "UltraLuxuryRange"]\n  },\n  "probabilities": [\n    [null, ["LocationType", "Urban"], [0.4, 0.5]],\n    [null, ["LocationType", "Suburban"], [0.3, 0.4]],\n    [null, ["LocationType", "Rural"], [0.2, 0.3]],\n    \n    [null, ["PropertyType", "EntireHomeApartment"], [0.5, 0.6]],\n    [null, ["PropertyType", "PrivateRoom"], [0.3, 0.4]],\n    [null, ["PropertyType", "SharedRoom"], [0.05, 0.1]]